export const ALL_MERCHANT_REQUEST = "ALL_MERCHANT_REQUEST"
export const ALL_MERCHANT_SUCCESS = "ALL_MERCHANT_SUCCESS"
export const ALL_MERCHANT_FAIL = "ALL_MERCHANT_FAIL"

export const MERCHANT_DETAILS_REQUEST = "MERCHANT_DETAILS_REQUEST"
export const MERCHANT_DETAILS_SUCCESS = "MERCHANT_DETAILS_SUCCESS"
export const MERCHANT_DETAILS_FAIL = "MERCHANT_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"