export const ALL_OFFER_REQUEST = "ALL_OFFER_REQUEST"
export const ALL_OFFER_SUCCESS = "ALL_OFFER_SUCCESS"
export const ALL_OFFER_FAIL = "ALL_OFFER_FAIL"

export const OFFER_DETAILS_REQUEST = "OFFER_DETAILS_REQUEST"
export const OFFER_DETAILS_SUCCESS = "OFFER_DETAILS_SUCCESS"
export const OFFER_DETAILS_FAIL = "OFFER_DETAILS_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"